# Generated by Django 3.1.4 on 2020-12-29 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('parent_name', models.CharField(default='No plot name available', max_length=200)),
                ('variation_name', models.CharField(default='No plot name available', max_length=200, primary_key=True, serialize=False)),
                ('synonyms', models.CharField(default='No synonyme available', max_length=200)),
                ('goals', models.JSONField()),
                ('dimensionality', models.CharField(default='No dimensionality info available', max_length=200)),
                ('numerical', models.CharField(max_length=200)),
                ('categorical', models.IntegerField(default=0)),
                ('visual_cues', models.JSONField()),
                ('coordinate_system', models.JSONField()),
                ('shapes', models.JSONField()),
                ('description', models.TextField(default='No description available')),
                ('anatomy', models.TextField(default='No anatomy info available')),
                ('caveats', models.TextField(default='No caveat info available')),
                ('facetted', models.BooleanField()),
                ('single_facetted', models.BooleanField()),
                ('dual_facetted', models.BooleanField()),
                ('grouped', models.BooleanField()),
                ('plot_package', models.CharField(default='No plot package info available', max_length=200)),
                ('related', models.JSONField()),
                ('implemented', models.BooleanField(default=False)),
                ('icon', models.FilePathField(path='img/icon/')),
                ('seaborn_plot', models.FilePathField(path='img/seaborn/')),
                ('plotly_plot', models.FilePathField(path='img/plotly/')),
                ('plotly_code', models.CharField(default='No code available', max_length=200)),
            ],
        ),
    ]
