# Generated by Django 3.1 on 2020-12-06 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('name', models.CharField(default='No plot name available', max_length=200, primary_key=True, serialize=False)),
                ('image', models.FilePathField(path='/img')),
            ],
        ),
    ]
