# Generated by Django 3.1 on 2020-12-17 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('parent_name', models.CharField(default='No plot name available', max_length=200)),
                ('variation_name', models.CharField(default='No plot name available', max_length=200, primary_key=True, serialize=False)),
                ('synonyms', models.CharField(default='No synonyms', max_length=200)),
                ('goals', models.CharField(default='No goals available', max_length=200)),
                ('dimensionality', models.CharField(default='No dimensionality info available', max_length=200)),
                ('numerical', models.CharField(max_length=200)),
                ('categorical', models.CharField(max_length=200)),
                ('visual_cues', models.CharField(default='No visual cue info available', max_length=200)),
                ('coordinate_system', models.CharField(default='No coordinate system info available', max_length=200)),
                ('shapes', models.CharField(default='No shape info available', max_length=200)),
                ('description', models.TextField(default='No description available')),
                ('anatomy', models.TextField(default='No anatomy info available')),
                ('caveats', models.TextField(default='No caveat info available')),
                ('facetted', models.BooleanField()),
                ('single_facetted', models.BooleanField()),
                ('dual_facetted', models.BooleanField()),
                ('grouped', models.BooleanField()),
                ('plot_package', models.CharField(default='No plot package info available', max_length=200)),
                ('related', models.CharField(default='No info for related plot available', max_length=200)),
                ('implemented', models.BooleanField(default=False)),
                ('icon', models.FilePathField(path='img/icon/')),
                ('seaborn', models.FilePathField(path='img/seaborn/')),
            ],
        ),
    ]
